exclude: ^lib  # flake8: noqa
repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.19.4
    hooks:
      - id: pyupgrade
        args:
          - --py3-plus
          - --py36-plus
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: pretty-format-json
        args:
          - --autofix
        exclude: ^tests/.+/profiles.d/.*
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [--exclude, tests]
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
      - id: reorder-python-imports
        name: Reorder Python imports (sac_configurations, tests)
        files: "^(?!examples/)"
        args: ["--application-directories", "src/sac_configurations"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
  - repo: https://github.com/yunojuno/pre-commit-xenon
    rev: v0.1
    hooks:
      - id: xenon
        args:
          [
            "--max-average=B",
            "--exclude=local*",
            "--ignore=lib_*,local*,target,tests",
          ]
  - repo: https://github.com/pycqa/pylint
    rev: v2.8.3
    hooks:
      - id: pylint
        args: ['--disable=C0411,E0401,F0401,R0902,W0212,W0105,W0107,C0415,W0613,R0913,R0912,R0914', '--max-line-length=200']
        types: [python]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
  - repo: local
    hooks:
      - id: pytest-cov
        name: pytest-cov
        stages: [commit]
        language: system
        entry:  pytest -v --cov-config=setup.cfg --cov-fail-under=85 --cov-report term-missing
        types: [python]
        pass_filenames: false
        always_run: true
